### ISSUE TITLE
MBN vert colors for some stages not correct

### ISSUE THREAD

**Issue by Demonslayerx8** [gdkchan/SPICA#11]
As title says. MBN stages in smash3ds have vert colors not correct (like it used to be in Ohana Rebirth), and even tho the model is properly rigged to the bone(s), it seems like single binded models don't save their positions after being exported, meaning the model is being moved to 0,0,0, while the bone stays put to where it goes.

![vert colors wrong](https://cloud.githubusercontent.com/assets/17195757/26407407/e6fa1036-404f-11e7-9e3a-187c6210aabd.png)
![model not positioned to bone](https://cloud.githubusercontent.com/assets/17195757/26407483/21bfe3e4-4050-11e7-9f35-4219f893af7b.png)

**Comment by gdkchan** [comment]
IIRC I only implemented rigid skinned meshes transforming on the SMD exporter, but not on the DAE exporter since it would be more complicated due to the way how DAE is structured (basically I would need to create a new vertex buffer with all meshes transformed and then create a new indices buffer that would be used on DAE), so I decided to do this later.

About the mbn issue well, at least the textures are correct now 😄 Can you say which models have the color issue? (Just two or three is enough so I know what to use to test this).

**Comment by Demonslayerx8** [comment]
for the vertex colors, characters are fine, for stages... Gerudo Valley Omega, Hyrule Castle Omega, Magicant Sky, Midgar Ring Omega, Unova Pokemon Leage

if you want anymore, i can search.

**Comment by gdkchan** [comment]
The second problem (meshes being at origin rather that at bone position) should be fixed by eee2a10abf1ab0b00418d25723b36f00cb4e2852 (let me known if it isn't), i'll look into the color issue when I have more time.

**Comment by Demonslayerx8** [comment]
Yep, model is now fixed to the bone position! Now i'll be waiting for the color fixes.
![model positioned to bone](https://cloud.githubusercontent.com/assets/17195757/26432155/80eff9e0-40ae-11e7-83aa-b406127466d0.png)

**Comment by gdkchan** [comment]
Color issue should be fixed on ccdba3df13ba0889e6ce2b3d70e2e1740e9d4bf4 (please confirm).

**Comment by Demonslayerx8** [comment]
displays the colors properly now, thanks~
