### ISSUE TITLE
Unable to open Sun/Moon interior models & textures

### ISSUE THREAD

**Issue by NickGurMatic69** [gdkchan/SPICA#24]
I'm getting an unsupported file format error with this interior model from garc a/0/8/6, I can open this in Ohana.

dec_0571.bin unpacked https://mega.nz/#!kkhlxTYL!zy17t0KGJ3NpNsp5ESu97alXN5T2e8kKRSsTB53wfMg

Also unable to open textures from a/0/8/3

dec_1761.bin 0_BG https://mega.nz/#!xlQ3VQzD!8KqGRmeZFhCtqIedvfLLgia3kuJjJjl9oX44TRwACYk

**Comment by gdkchan** [comment]
I added support for that on 52515eaa8b5fc89c3959cccd09b6767530196f84.

Was originally planning to support the entire container with the model/texture files but I guess theres no reason to not support the raw files too. I also plan to change the way how the identifier works to be more efficient (and move it outside of the winforms project since I'll need it on the CLI interface too).
