### ISSUE TITLE
sumo model export broken textures or uvmap idk

### ISSUE THREAD

**Issue by d3athrow** [gdkchan/SPICA#44]
when imported into blender from smd format and textures applied seems something messes up in the exporting process.

![img](http://ss13.moe/uploads/2018-02-08_11-07-56.gif)

**Comment by igniscitrinus** [comment]
Pokémon GfModels make heavy use of texture repeating and mirroring across the board, presumably to save space on redundant textures. 
Collada supports texture mirroring and repeating as wrapping modes, which SPICA applies accordingly on export; SMD unfortunately doesn't support this.

The best workaround for this is to mirror the textures to match the UVs manually. There's no consistent method, but as a general rule they go as follows:

- Body, Mouth and Eye textures are mirrored once
![image](https://user-images.githubusercontent.com/14958008/36008299-fd82eca0-0d46-11e8-9623-5e39bc8b99a3.png)
![image](https://user-images.githubusercontent.com/14958008/36008314-0d4c3434-0d47-11e8-9328-ad54a19bf12e.png)
![image](https://user-images.githubusercontent.com/14958008/36008338-1fa6e1ba-0d47-11e8-8fa8-ef4d0e130a58.png)

- Iris textures are flipped horizontally, mirrored four times horizontally, repeated four times vertically, then the middle of the alpha mask from the Eye/Iris Normal map is applied over it (Demonstrated with Bulbasaur, since Flareon doesn't have any iris textures)
![image](https://user-images.githubusercontent.com/14958008/36008695-e8619388-0d48-11e8-9a82-5a17e40e6aae.png)
![image](https://user-images.githubusercontent.com/14958008/36008801-4986a05e-0d49-11e8-81db-6e2cff12070d.png)
![image](https://user-images.githubusercontent.com/14958008/36008868-a7c8dae2-0d49-11e8-9fc8-6d7a25c3633a.png)

Apologies if this makes little sense, this entire process is really convoluted.

Additionally, some Pokémon might not have any mirrored textures at all, some might not need the iris to be flipped beforehand, etc.
Ultimately, it all boils down to trial and error and seeing what looks right and what doesn't.

**Comment by d3athrow** [comment]
Oh, thanks for the helpful info.

**Comment by milankarman** [comment]
@igniscitrinus Hey man, stumbled onto your response to this issue just now while trying to import a bulbasaur model into unity. I'm having a ton of trouble trying to get the alpha mask to make the eyes fit. I adjusted the image to match the eyes and I'm pretty sure everything is in the right place. I'm not sure though how you actually get the transparency of the alpha mask onto the iris. This is what I got so far.
![unity_2018-09-18_04-09-16](https://user-images.githubusercontent.com/34920368/45660368-a6ece980-baf8-11e8-9b67-7a1e57fb26ab.png)

You seem very knowledgeable on this so I was hoping you could help. Thanks in advance :)
